{"uuid": "1f815177-de40-408c-ad8c-4d0b6081699f", "children": ["0bdad297-8895-4df2-a2dd-74ac4c20fea8"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\tests\\conftest.py\", line 7, in browser\n    browser = webdriver.Firefox()\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 68, in __init__\n    super().__init__(command_executor=executor, options=self.options)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\afisher\\Documents\\PythonYaPracticum\\Sprint4__\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1689923022229, "stop": 1689923026351}], "start": 1689923022229, "stop": 1689923026411}